export const PHYSICS = {
      GRAVITY_BASE : 0.05,
      BASS_MULTIPLIER : 3.0,

      TREBLE_MULTIPLIER : 40.0,

      DAMPING : 0.01,

      PARTICLE_RADIUS : 4,

      RESTITUTION : 0.9,

      SPATIAL_CELL_SIZE : 16,

      MID_PULL_FORCE : 0.25,
      BASS_PUSH_FORCE : 5.0,

      MOUSE_PULL_FORCE: 1.5,           
      MOUSE_INTERACTION_RADIUS: 150,     
      SHOCKWAVE_PUSH_FORCE: 15.0,       
      SHOCKWAVE_EXPANSION_SPEED: 20,
};